services:
  flask:
    image: flask-dev
    container_name: flask
    ports:
      - "8000:8000"
      - "9001:9001"
      - "2123:22"
    volumes:
      - document_root:/app
    networks:
      - dev

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpass
      POSTGRES_DB: flaskdb
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - dev

  developer:
    image: developer-dev
    container_name: developer
    ports:
      - "5901:5901"
      - "2124:22"
    volumes:
      - document_root:/home/ubuntu/workspace
    networks:
      - dev

volumes:
  dbdata:
  document_root:

networks:
  dev:
    driver: bridge
